// Spiritual Master & Initiation Place options (paste exactly)
export const SPIRITUAL_MASTERS = [
  "H.H. Bhakti Tirtha Swāmi",
  "H.G. Bhurijana Prabhu",
  "H.G. Caitanya Candra Caran Prabhu",
  "H.G. Caitanya Candra Prabhu",
  "H.G. Caru Prabhu",
  "H.G. Druktakarma Prabhu",
  "H.G. Harivilasa Prabhu",
  "H.G. Kālakaṇṭha Prabhu",
  "H.G. Kratu Prabhu",
  "H.G. Kripamoya Prabhu",
  "H.G. Krsna Ksetra Prabhu",
  "H.G. Madhu Sevita Prabhu",
  "H.G. Mahāmana Prabhu",
  "H.G. Mahatma Prabhu",
  "H.G. Manonatha Prabhu",
  "H.G. Matsya Avatara Prabhu",
  "H.G. Ravindra Svarupa Prabhu",
  "H.G. Saṅkarṣaṇa Prabhu",
  "H.G. Shyamlal Prabhu",
  "H.G. Vaisesika Prabhu",
  "H.G. Vedavyasa Prabhu",
  "H.G. Virabahu Prabhu",
  "H.H. Bhakti Bhṛiṅg Govind Swāmi",
  "H.H. Bhakti Bhushan Swāmi",
  "H.H. Bhakti Caitanya Swāmi",
  "H.H. Bhakti Cāru Swāmi",
  "H.H. Bhakti Dhīr Damodar Swāmi",
  "H.H. Bhakti Gaurava Narayan Swāmi",
  "H.H. Bhakti Prema Swami",
  "H.H. Bhakti Rāghava Swāmi",
  "H.H. Bhakti Sarbaswa Govind Swāmi",
  "H.H. Bhakti Sundara Swāmi",
  "H.H. Bhakti Svarupa Dāmodar Swāmi",
  "H.H. Bhakti V V Narsimha Swāmi",
  "H.H. Bhakti Vaibhava Puri Swāmi",
  "H.H. Bhakti Vaibhava Swami",
  "H.H. Bhakti Vidyā Pūrṇ̣a Swāmi",
  "H.H. Bhakti Vijñāna Goswāmi",
  "H.H. Bhakti Vikās Swāmi",
  "H.H. Bhakti Visrambha Madhava Swāmi",
  "H.H. Bhakti Vrajendranandana Swāmi",
  "H.H. Bhaktimārga Swāmi",
  "H.H. Bhaktivedanta Narayana Swami",
  "H.H. Bira Krṣna Swāmi",
  "H.H. Candramauli Swami",
  "H.H. Chandra Mukha Swāmi",
  "H.H. Dānvira Swāmi",
  "H.H. Devāṃrta Swāmi",
  "H.H. Dhanurdhara Swāmi",
  "H.H. Dhanvantari Swāmi",
  "H.H. Giridhārī Swāmi",
  "H.H. Girirāja Swāmi",
  "H.H. Gopāla Kṛṣṇa Goswāmi",
  "H.H. Guṇagrahi Swāmi",
  "H.H. Guru Prasād Swāmi",
  "H.H. Haladhara Swāmi",
  "H.H. Hanumātpreṣaka Swāmi",
  "H.H. Harikeśa Swāmi",
  "H.H. Indradyumna Swāmi",
  "H.H. Janananda Goswami",
  "H.H. Jayadvaita Swāmi",
  "H.H. Jayapatākā Swāmi",
  "H.H. Kadamba Kānan Swāmi",
  "H.H. Kavicandra Swāmi",
  "H.H. Kīrtanānanda Swāmi",
  "H.H. Kṛṣṇadās Swāmi",
  "H.H. Lokanātha Swāmi",
  "H.H. Maha Vishnu Swāmi",
  "H.H. Mahāviṣṇu Swāmi",
  "H.H. Māhāndhi Swāmi",
  "H.H. Nava Yogendra Swāmi",
  "H.H. Nirañjana Swāmi",
  "H.H. Pārtha Sārthidās Swāmi",
  "H.H. Prabha Viṣṇu Swāmi",
  "H.H. Prahlādnanda Swāmi",
  "H.H. Puruṣatraya Swāmi",
  "H.H. Rādhanātha Swāmi",
  "H.H. Rādhā Govind Swāmi",
  "H.H. Romapāda Swāmi",
  "H.H. Rtadhvaja Swāmi",
  "H.H. Sacinandan Swāmi",
  "H.H. Satsvarūpa Dāsa Goswāmi",
  "H.H. Sivarāma Swāmi",
  "H.H. Smit Kṛṣṇa Swāmi",
  "H.H. Subhāga Swāmi",
  "H.H. Tamālakṛṣṇa Goswāmi",
  "H.H. Trivikrama Swāmi",
  "H.H. Varsana Swami",
  "H.H. Vedavyāsa Priyā Swāmi",
  "His Divine Grace A.C. Bhaktivedanta Swami Prabhupada",
  "Gaudiya Matha",
];
