// Spiritual Master & Initiation Place options (paste exactly)
export const SPIRITUAL_MASTERS = [
  "H.H. Rādhanātha Swāmi",
  "Gaudiya Matha",
  "H.H. Bhakti Tirtha Swāmi",
  "H.D.G.B.S. Tirtha Swāmi",
  "H.G. Bhurijana Prabhu",
  "H.G. Caitanya Candra Caran Prabhu",
  "H.G. Caitanya Candra Prabhu",
  "H.G. Caru Prabhu",
  "H.G. Druktakarma Prabhu",
  "H.G. Harivilasa Prabhu",
  "H.G. Kālakaṇṭha Prabhu",
  "H.G. Kratu Prabhu",
  "H.G. Kripamoya Prabhu",
  "H.G. Krsna Ksetra Prabhu",
  "H.G. Madhu Sevita Prabhu",
  "H.G. Mahāmana Prabhu",
  "H.G. Mahatma Prabhu",
  "H.G. Manonatha Prabhu",
  "H.G. Matsya Avatara Prabhu",
  "H.G. Ravindra Svarupa Prabhu",
  "H.G. Saṅkarṣaṇa Prabhu",
  "H.G. Shyamlal Prabhu",
  "H.G. Vaisesika Prabhu",
  "H.G. Vedavyasa Prabhu",
  "H.G. Virabahu Prabhu",
  "H.H. Bhakti Bhṛiṅg Govind Swāmi",
  "H.H. Bhakti Bhushan Swāmi",
  "H.H. Bhakti Caitanya Swāmi",
  "H.H. Bhakti Cāru Swāmi",
  "H.H. Bhakti Dhīr Damodar Swāmi",
  "H.H. Bhakti Gaurava Narayan Swāmi",
  "H.H. Bhakti Prema Swami",
  "H.H. Bhakti Rāghava Swāmi",
  "H.H. Bhakti Sarbaswa Govind Swāmi",
  "H.H. Bhakti Sundara Swāmi",
  "H.H. Bhakti Svarupa Dāmodar Swāmi",
  "H.H. Bhakti V V Narsimha Swāmi",
  "H.H. Bhakti Vaibhava Puri Swāmi",
  "H.H. Bhakti Vaibhava Swami",
  "H.H. Bhakti Vidyā Pūrṇ̣a Swāmi",
  "H.H. Bhakti Vijñāna Goswāmi",
  "H.H. Bhakti Vikās Swāmi",
  "H.H. Bhakti Visrambha Madhava Swāmi",
  "H.H. Bhakti Vrajendranandana Swāmi",
  "H.H. Bhaktimārga Swāmi",
  "H.H. Bhaktivedanta Narayana Swami",
  "H.H. Bira Krṣna Swāmi",
  "H.H. Candramauli Swami",
  "H.H. Chandra Mukha Swāmi",
  "H.H. Dānvira Swāmi",
  "H.H. Devāṃrta Swāmi",
  "H.H. Dhanurdhara Swāmi",
  "H.H. Dhanvantari Swāmi",
  "H.H. Giridhārī Swāmi",
  "H.H. Girirāja Swāmi",
  "H.H. Gopāla Kṛṣṇa Goswāmi",
  "H.H. Guṇagrahi Swāmi",
  "H.H. Guru Prasād Swāmi",
  "H.H. Haladhara Swāmi",
  "H.H. Hanumātpreṣaka Swāmi",
  "H.H. Harikeśa Swāmi",
  "H.H. Indradyumna Swāmi",
  "H.H. Janananda Goswami",
  "H.H. Jayadvaita Swāmi",
  "H.H. Jayapatākā Swāmi",
  "H.H. Kadamba Kānan Swāmi",
  "H.H. Kavicandra Swāmi",
  "H.H. Kīrtanānanda Swāmi",
  "H.H. Kṛṣṇadās Swāmi",
  "H.H. Lokanātha Swāmi",
  "H.H. Maha Vishnu Swāmi",
  "H.H. Mahāviṣṇu Swāmi",
  "H.H. Māhāndhi Swāmi",
  "H.H. Nava Yogendra Swāmi",
  "H.H. Nirañjana Swāmi",
  "H.H. Pārtha Sārthidās Swāmi",
  "H.H. Prabha Viṣṇu Swāmi",
  "H.H. Prahlādnanda Swāmi",
  "H.H. Puruṣatraya Swāmi",
  "H.H. Rādhā Govind Swāmi",
  "H.H. Romapāda Swāmi",
  "H.H. Rtadhvaja Swāmi",
  "H.H. Sacinandan Swāmi",
  "H.H. Satsvarūpa Dāsa Goswāmi",
  "H.H. Sivarāma Swāmi",
  "H.H. Smit Kṛṣṇa Swāmi",
  "H.H. Subhāga Swāmi",
  "H.H. Tamālakṛṣṇa Goswāmi",
  "H.H. Trivikrama Swāmi",
  "H.H. Varsana Swami",
  "H.H. Vedavyāsa Priyā Swāmi",
  "His Divine Grace A.C. Bhaktivedanta Swami Prabhupada",
];

export const INITIATION_PLACES = [
  "Lisnaskea",
  "Buenos Aires - Bhaktivedanta Center",
  "Adelaide",
  "Brisbane",
  "Canberra",
  "Gold Coast.Bhakti Center",
  "Melbourne",
  "Melbourne - Crossways",
  "Millfield",
  "Murwillumbah",
  "New Gokula Farm",
  "Newcastle",
  "Otford",
  "Perth",
  "Sydney",
  "Sydney - New Gokula Farm",
  "Vienna",
  "Bahrain",
  "Chittagong - Sri Sri Radha Madhava Mandir",
  "Radhadesh",
  "Sarajevo",
  "Belo Horizonte",
  "Campina Grande",
  "ISKCON Porto Alegre",
  "Aheloy",
  "Sofia-Bulgaria",
  "Ashcroft - Saranagati Eco Village",
  "Brampton - Bhaktivedanta Cultural Center",
  "Calgary",
  "Edmonton",
  "Halifax",
  "Montreal",
  "Ottowa",
  "Regina",
  "Scarborough",
  "Toronto",
  "Vancouver",
  "ISKCON Santiago, Chile",
  "Hong Kong",
  "Shanghai -China",
  "Croatia",
  "Dubronik",
  "Karlovac",
  "Lendava",
  "Ceca",
  "Harinam Mandir",
  "Harinam Mandir Luzce",
  "Prague",
  "Copenhagen",
  "Santo Domingo",
  "Tallinn-Sri Harinama Mandir",
  "Fiji",
  "Helsinki",
  "Chateauroux – La Nouvelle Mayapura",
  "ISKCON Paris",
  "Abenteuer Berlin",
  "Bhakti Yoga Zentrum",
  "Gaurdesh Cologne",
  "Hamburg",
  "Heidelberg",
  "Leipzig",
  "Munich",
  "Simhachalam Temple in Germany",
  "Weisbaden Rehein main taunus",
  "Accra(Ghana)",
  "Georgetown",
  "Budapest",
  "Adilabad",
  "Agartala",
  "Ahmedabad",
  "Ahmednagar",
  "Ahmedpur",
  "Ajmer",
  "Akola",
  "Aligarh",
  "Allahabad",
  "Alleppey",
  "Amritsar",
  "Arvade",
  "Aurangabad",
  "Aurangabad - Central",
  "Bangalore-Sri Jagannath Mandir",
  "Baramati",
  "Baroda",
  "Beed",
  "Belgaum",
  "Berhampur",
  "Bhagalpur",
  "Bhaktivedanta Hospital - Mumbai",
  "Bhilwara",
  "Bhosari",
  "Bhubaneswar",
  "Bhusawal",
  "Boisar",
  "BRC Kolkata",
  "Chalisgaon (Nasik Ext Center)",
  "Chandigarh",
  "Chennai",
  "Chiplun (Chowpatty-Ext Center)",
  "Coimbatore",
  "Cuttack",
  "Dapoli",
  "Davangere",
  "Degloor, Parbhani",
  "Dehradun",
  "Delhi",
  "Deulgaon Parbhani",
  "Dewas",
  "Dhanaupur",
  "Dhanbad",
  "Dharmapuri, Parbhani",
  "Dharwad",
  "Dhule (Nasik Ext Center)",
  "Dibrugrah ext center",
  "Dwarka",
  "Etawah (ISKCON)",
  "Faridabad",
  "Gadei Giri",
  "Gandhidham (Kutch)",
  "Gaya",
  "GEV",
  "Goa - Madgaon",
  "Goa - Mapusa",
  "Goa - Panaji",
  "Goa - Ponda",
  "Goa - Vasco",
  "Govardhan",
  "Guntur",
  "Gurugram",
  "Guwahati",
  "Gwalior",
  "Habibpur",
  "Hadgaon",
  "Hadgoan, Parbhani",
  "Haldia",
  "Hanamkonda",
  "Haridaspur",
  "Haridwar",
  "Hingoli",
  "Holynames School (Assam)",
  "Hyderabad",
  "ICC-Bangalore",
  "Imphal",
  "Indore",
  "ISKCON Whitefield, Bangalore",
  "Jaipur",
  "Jalandhar",
  "Jalna",
  "Jamkhed",
  "Jammu",
  "Juhu",
  "Kankavali",
  "Kanpur",
  "Kanyakumari",
  "Karwar",
  "Katra",
  "Khalisai",
  "Kharagpur",
  "Kharghar",
  "Kinhola",
  "Kinhola, parbhani",
  "Kochi",
  "Kolhapur",
  "Kolkata.Albert Road",
  "Kolkata.Dumdum",
  "Kolkata.New town",
  "Koregaon",
  "Kurukshetra",
  "Latur",
  "Lonere",
  "Lucknow",
  "Ludhiana",
  "Madikeri",
  "Madurai",
  "Malaysia",
  "Mangalore",
  "Mayapur",
  "Medchal",
  "Metpally",
  "Mira Road",
  "Miraj",
  "Moirang",
  "Mumbai.Chowpatty",
  "Mysore",
  "Nagpur",
  "Nanded",
  "Narasaraopet",
  "Nashik",
  "Navi Mumbai-India",
  "New Delhi.Dwarka",
  "New Delhi.East of Kailash",
  "New Delhi.Panjabi Bagh",
  "Nigdi",
  "Nizamabad",
  "Noida",
  "Not in use",
  "NOT IN USE-1",
  "NOT IN USE-3",
  "Pachora",
  "Palghar",
  "Pandharpur",
  "Panihati",
  "Parbani",
  "Patna",
  "Pen",
  "Prodattur",
  "Pudukkottai",
  "Pune",
  "Pune BCEC (Vishal Nagar)",
  "Puri.Bhaktivedanta Asram",
  "Puri.Swargadwar",
  "Raipur",
  "Rajahmundry",
  "Rajapur",
  "Ranaghat",
  "Ranchi",
  "Ratnagiri",
  "Raurkela",
  "Remuna",
  "Rishikesh",
  "Roha",
  "Sangamner",
  "Satara",
  "Secunderabad",
  "Sheikh Rajur, Parbhani",
  "Shirpur (Nasik Ext Center)",
  "Silchar",
  "Siliguri",
  "Solapur",
  "Sri Rangam",
  "Surat",
  "Tadkalas, Parbhani",
  "Tembhurani",
  "Tenali",
  "Thane",
  "Thiruvananthapuram",
  "Tirupati",
  "Udaipur",
  "Udgir",
  "Udhampur",
  "Udipi",
  "Ujjain",
  "Vallabh Vidyanagar",
  "Varanasi",
  "Vijayawada",
  "Vishakapatnam",
  "Vrindavan",
  "Warangal",
  "Washim",
  "Jakarta",
  "Tehran",
  "Dublin",
  "ISKCON Harish",
  "ISKCON Tel Aviv",
  "Centro Govinda (Milano)",
  "Centro Govinda (Roma)",
  "Centro Hare Krishna Torino",
  "Centro Vaikuntha (Bologna)",
  "Nava Rama Rajya (Lecce)",
  "Nitai Gaura Premanande (Traveling Temple)",
  "Prabhupadadesh (Vicenza)",
  "Rome Sankirtan Dham Italy",
  "Villa Vrindavana (Florence)",
  "Villaggio Hare Krishna (Bergamo)",
  "Tokyo",
  "Almaty",
  "Almaty1",
  "Nairobi",
  "Kuwait",
  "Latvija Riga",
  "Kaunas",
  "LITHUANIA VILNIUS",
  "Maisekiu center for vedic culture",
  "New Dwarika Lithuania Vilnius",
  "Malawi",
  "Air Keroh",
  "Alor Setar",
  "Bahau",
  "Batu Berendam",
  "Bedong",
  "Bentong",
  "Bukit Mertajam",
  "Ipoh",
  "Johor Bahru",
  "Klang",
  "Kluang",
  "Kuala Lumpur",
  "Kuantan",
  "Kuching",
  "Kulim",
  "Malau",
  "Mentakap",
  "Penang Island",
  "Perai",
  "Port Dickson",
  "Seremban",
  "Sitiawan",
  "Skudai",
  "Sungai Petani",
  "Taiping",
  "Teluk Intan",
  "Phoenix",
  "Uruapan",
  "Kishinev",
  "Tiraspol",
  "Myanmar",
  "Butwal,Nepal",
  "Kathmandu",
  "Amsterdam",
  "Den Hague",
  "Auckland - New Zealand",
  "Wellington - New Zealand",
  "Lagos",
  "Oslo-Norway",
  "Muscat",
  "Karachi",
  "Panama",
  "Manila",
  "New Raman Reti",
  "Lisbon",
  "Doha",
  "Timisoara",
  "Armavir",
  "Astrakhan",
  "Barnaul",
  "Belarus",
  "Chelyabinsk",
  "Chita",
  "Ekaterinburg",
  "Ekaterinburg Esentuki",
  "Habarovsk",
  "Irkutsk",
  "Kazan",
  "Kislovodsk",
  "Krasnodar",
  "Krasnoyarsk",
  "Kurgan",
  "Kurjinovo",
  "Kursk",
  "Magnitogorsk",
  "Minsk",
  "Moscow",
  "Moscow - Sri Sri Radha Madhav",
  "Moscow-Sri Jagannath Mandir",
  "Murmansk",
  "Nalchic city",
  "Nijni Novogorod",
  "Nijny Novgorod",
  "Nizhny Tagil",
  "NOT IN USE-2",
  "Novorossijsk",
  "Novorossiysk",
  "Novosibirsk",
  "Omsk",
  "Perm",
  "Rostov",
  "Sahalin",
  "Saint Petersburg",
  "Samara",
  "Simbirsk",
  "Smolensk",
  "Sochi",
  "Toglyatty",
  "Tula",
  "Tyumen",
  "Ulan-Ude",
  "Vladimir",
  "Vladivostok",
  "Yaroslavl",
  "Singapore",
  "Ljubljana",
  "Ljubljana, New Yogapitha",
  "CapeTown",
  "Durban",
  "Midrand",
  "Pietermaritzburg",
  "Gothenburg",
  "Stockholm",
  "Zurich",
  "Taiwan",
  "Dar Es Salaam",
  "Bangkok",
  "Port of Spain Trinidad",
  "Chernigov",
  "Chernivtsi",
  "Chortkov",
  "Dnepropetrovsk",
  "Donetsk",
  "Harkov",
  "Kherson",
  "Kiev",
  "Krivoy Rog",
  "Kropyvnytskyi",
  "Lugansk",
  "Lviv",
  "Mariupol",
  "Nikolaev",
  "Odessa",
  "Poltava",
  "Rivne",
  "Rovno",
  "simferopol",
  "Sumy",
  "Ternopil",
  "Uzhgorod",
  "Vinnitsa",
  "Zaporizhzhya",
  "Abu Dhabi",
  "Ajman",
  "Dubai",
  "Fujairah",
  "Ras al-Khaimah",
  "Sharjah",
  "Umm al-Quwain",
  "Belfast",
  "Berbice",
  "Birmingham UK",
  "Canterbury",
  "Coventry",
  "Crawley",
  "Glasgow",
  "Ireland",
  "Leicester",
  "Liverpool",
  "London.Bhaktivedanta Manor",
  "London.Camden",
  "London.Soho",
  "London.South Norwood",
  "Manchester",
  "Newcastle-upon-Tyne",
  "Plymouth",
  "Romford",
  "Scotland",
  "Wales",
  "Alachua",
  "Albany",
  "Atlanta",
  "Austin",
  "Baltimore",
  "Berkeley",
  "Bloomington",
  "Bogota",
  "Boise",
  "Boise, Idaho",
  "Boston",
  "Brooklyn",
  "Carriere-New Talavan",
  "Central New Jersey",
  "Charlotte",
  "Chicago",
  "Cleveland",
  "Columbus",
  "Crane",
  "Dallas",
  "Deland Florida",
  "Delaware",
  "Denver",
  "Detroit",
  "East Hartford Temple",
  "Farmington Hills",
  "Gainesville",
  "Gita Nagari.Port Royal",
  "Grand Rapids",
  "Gurabo.New Govardhan Hill",
  "Hartford",
  "Hillsborough.New Goloka",
  "Honolulu",
  "Houston",
  "Kansas City",
  "Laguna Beach",
  "Las Vegas",
  "Long Island",
  "Los Angeles",
  "Miami",
  "Minneapolis",
  "Murari Sevaka.Mulberry",
  "Naperville",
  "New Jersey",
  "New Orleans",
  "New Vrindavan.Moundsville",
  "New York",
  "New York-Bhakti Center",
  "paramaribo",
  "Philadelphia",
  "Phoenix, Arizona",
  "Portland",
  "Potomac",
  "Queens",
  "Sacramanto CA",
  "Salt Lake City UTah",
  "San Diego",
  "San Jose",
  "Sandy Ridge",
  "Seattle",
  "Silicon Valley",
  "Spanish Fork Utah",
  "St. Louis",
  "Tallahassee",
  "Tampa",
  "Towaco",
  "Tucson",
  "Washington",
  "Tashkent",
  "Zambia",
];
